# Generated by Django 4.2 on 2023-04-21 06:03

import apps.informations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Basic_Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=30
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("birth_time", models.TimeField()),
                (
                    "Mother_Tongue",
                    models.CharField(
                        choices=[
                            ("Tamil", "Tamil"),
                            ("Telugu", "Telugu"),
                            ("Malayalam", "Malayalam"),
                            ("Kannada", "Kannada"),
                            ("Hindi", "Hindi"),
                            ("Others", "Others"),
                        ],
                        default="Tamil",
                        max_length=120,
                    ),
                ),
                (
                    "photo1",
                    models.ImageField(upload_to=apps.informations.models.upload_to),
                ),
                (
                    "photo2",
                    models.ImageField(upload_to=apps.informations.models.upload_to),
                ),
                (
                    "photo3",
                    models.ImageField(upload_to=apps.informations.models.upload_to),
                ),
                (
                    "photo4",
                    models.ImageField(upload_to=apps.informations.models.upload_to),
                ),
                (
                    "photo5",
                    models.ImageField(upload_to=apps.informations.models.upload_to),
                ),
                (
                    "height",
                    models.CharField(
                        choices=[
                            ("< 4 feet", "< 4 feet"),
                            ("4 feet 0 inch", "4 feet 0 inch"),
                            ("4 feet 1 inch", "4 feet 1 inch"),
                            ("4 feet 2 inch", "4 feet 2 inch"),
                            ("4 feet 3 inch", "4 feet 3 inch"),
                            ("4 feet 4 inch", "4 feet 4 inch"),
                            ("4 feet 5 inch", "4 feet 5 inch"),
                            ("4 feet 6 inch", "4 feet 6 inch"),
                            ("4 feet 7 inch", "4 feet 7 inch"),
                            ("4 feet 8 inch", "4 feet 8 inch"),
                            ("4 feet 9 inch", "4 feet 9 inch"),
                            ("4 feet 10 inch", "4 feet 10 inch"),
                            ("4 feet 11 inch", "4 feet 11 inch"),
                            ("5 feet 0 inch", "5 feet 0 inch"),
                            ("5 feet 1 inch", "5 feet 1 inch"),
                            ("5 feet 2 inch", "5 feet 2 inch"),
                            ("5 feet 3 inch", "5 feet 3 inch"),
                            ("5 feet 4 inch", "5 feet 4 inch"),
                            ("5 feet 5 inch", "5 feet 5 inch"),
                            ("5 feet 6 inch", "5 feet 6 inch"),
                            ("5 feet 7 inch", "5 feet 7 inch"),
                            ("5 feet 8 inch", "5 feet 8 inch"),
                            ("5 feet 9 inch", "5 feet 9 inch"),
                            ("5 feet 10 inch", "5 feet 10 inch"),
                            ("5 feet 11 inch", "5 feet 11 inch"),
                            ("6 feet 0 inch", "6 feet 0 inch"),
                            ("6 feet 1 inch", "6 feet 1 inch"),
                            ("6 feet 2 inch", "6 feet 2 inch"),
                            ("6 feet 3 inch", "6 feet 3 inch"),
                            ("6 feet 4 inch", "6 feet 4 inch"),
                            ("6 feet 5 inch", "6 feet 5 inch"),
                            ("6 feet 6 inch", "6 feet 6 inch"),
                            ("6 feet 7 inch", "6 feet 7 inch"),
                            ("6 feet 8 inch", "6 feet 8 inch"),
                            ("6 feet 9 inch", "6 feet 9 inch"),
                            ("6 feet 10 inch", "6 feet 10 inch"),
                            ("6 feet 11 inch", "6 feet 11 inch"),
                            ("7 feet > ", "7 feet >"),
                        ],
                        max_length=120,
                    ),
                ),
                ("weight", models.IntegerField()),
                (
                    "phisical_Status",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Physically Challanged", "Physically Challanged"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("Slim", "Slim"),
                            ("Average", "Average"),
                            ("Athletic", "Athletic"),
                            ("Heavy", "Heavy"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "complexion",
                    models.CharField(
                        choices=[
                            ("Very Fair", "Very Fair"),
                            ("Fair", "Fair"),
                            ("Average", "Average"),
                            ("Below Average", "Below Average"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "food_habit",
                    models.CharField(
                        choices=[
                            ("Veg", "Veg"),
                            ("Non Veg", "Non Veg"),
                            ("Eggetarian", "Eggetarian"),
                            ("Vegan", "Vegan"),
                        ],
                        max_length=120,
                    ),
                ),
                ("father_name", models.CharField(max_length=120)),
                ("father_job", models.CharField(max_length=120)),
                ("mother_name", models.CharField(max_length=120)),
                ("no_of_brother", models.IntegerField()),
                ("brother_married", models.BooleanField()),
                ("no_of_sister", models.IntegerField()),
                ("sister_married", models.BooleanField()),
                ("educational_qualification", models.CharField(max_length=120)),
                ("job", models.CharField(max_length=120)),
                ("income_per_month", models.CharField(max_length=120)),
                ("Religious", models.CharField(max_length=120)),
                ("contact_person", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=120)),
                ("contact_No", models.IntegerField()),
                ("whatsApp", models.IntegerField()),
                ("address", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("district", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Basic Information",
                "verbose_name_plural": "Basic_Informations",
            },
        ),
    ]
