# Generated by Django 4.2 on 2023-05-03 08:57

import apps.informations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="SubCaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subcaste", models.CharField(max_length=120)),
                (
                    "caste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="informations.caste",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasicInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=30
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("birth_time", models.TimeField()),
                (
                    "Mother_Tongue",
                    models.CharField(
                        choices=[
                            ("Tamil", "Tamil"),
                            ("Telugu", "Telugu"),
                            ("Malayalam", "Malayalam"),
                            ("Kannada", "Kannada"),
                            ("Hindi", "Hindi"),
                            ("Others", "Others"),
                        ],
                        default="Tamil",
                        max_length=120,
                    ),
                ),
                (
                    "Marital_Status",
                    models.CharField(
                        choices=[
                            ("Unmarried", "Unmarried"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                            ("Waiting for Divorce", "Waiting for Divorce"),
                        ],
                        default="Unmarried",
                        max_length=120,
                    ),
                ),
                (
                    "photo1",
                    models.ImageField(upload_to=apps.informations.models.upload_to),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.informations.models.upload_to,
                    ),
                ),
                (
                    "photo3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.informations.models.upload_to,
                    ),
                ),
                (
                    "photo4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.informations.models.upload_to,
                    ),
                ),
                (
                    "photo5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.informations.models.upload_to,
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        choices=[
                            ("< 4 feet", "< 4 feet"),
                            ("4 feet 0 inch", "4 feet 0 inch"),
                            ("4 feet 1 inch", "4 feet 1 inch"),
                            ("4 feet 2 inch", "4 feet 2 inch"),
                            ("4 feet 3 inch", "4 feet 3 inch"),
                            ("4 feet 4 inch", "4 feet 4 inch"),
                            ("4 feet 5 inch", "4 feet 5 inch"),
                            ("4 feet 6 inch", "4 feet 6 inch"),
                            ("4 feet 7 inch", "4 feet 7 inch"),
                            ("4 feet 8 inch", "4 feet 8 inch"),
                            ("4 feet 9 inch", "4 feet 9 inch"),
                            ("4 feet 10 inch", "4 feet 10 inch"),
                            ("4 feet 11 inch", "4 feet 11 inch"),
                            ("5 feet 0 inch", "5 feet 0 inch"),
                            ("5 feet 1 inch", "5 feet 1 inch"),
                            ("5 feet 2 inch", "5 feet 2 inch"),
                            ("5 feet 3 inch", "5 feet 3 inch"),
                            ("5 feet 4 inch", "5 feet 4 inch"),
                            ("5 feet 5 inch", "5 feet 5 inch"),
                            ("5 feet 6 inch", "5 feet 6 inch"),
                            ("5 feet 7 inch", "5 feet 7 inch"),
                            ("5 feet 8 inch", "5 feet 8 inch"),
                            ("5 feet 9 inch", "5 feet 9 inch"),
                            ("5 feet 10 inch", "5 feet 10 inch"),
                            ("5 feet 11 inch", "5 feet 11 inch"),
                            ("6 feet 0 inch", "6 feet 0 inch"),
                            ("6 feet 1 inch", "6 feet 1 inch"),
                            ("6 feet 2 inch", "6 feet 2 inch"),
                            ("6 feet 3 inch", "6 feet 3 inch"),
                            ("6 feet 4 inch", "6 feet 4 inch"),
                            ("6 feet 5 inch", "6 feet 5 inch"),
                            ("6 feet 6 inch", "6 feet 6 inch"),
                            ("6 feet 7 inch", "6 feet 7 inch"),
                            ("6 feet 8 inch", "6 feet 8 inch"),
                            ("6 feet 9 inch", "6 feet 9 inch"),
                            ("6 feet 10 inch", "6 feet 10 inch"),
                            ("6 feet 11 inch", "6 feet 11 inch"),
                            ("7 feet > ", "7 feet >"),
                        ],
                        max_length=120,
                    ),
                ),
                ("weight", models.IntegerField()),
                (
                    "phisical_Status",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Physically Challanged", "Physically Challanged"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("Slim", "Slim"),
                            ("Average", "Average"),
                            ("Athletic", "Athletic"),
                            ("Heavy", "Heavy"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "complexion",
                    models.CharField(
                        choices=[
                            ("Very Fair", "Very Fair"),
                            ("Fair", "Fair"),
                            ("Average", "Average"),
                            ("Below Average", "Below Average"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "food_habit",
                    models.CharField(
                        choices=[
                            ("Veg", "Veg"),
                            ("Non Veg", "Non Veg"),
                            ("Eggetarian", "Eggetarian"),
                            ("Vegan", "Vegan"),
                        ],
                        max_length=120,
                    ),
                ),
                ("father_name", models.CharField(max_length=120)),
                ("father_job", models.CharField(max_length=120)),
                ("mother_name", models.CharField(max_length=120)),
                ("mother_job", models.CharField(max_length=120)),
                ("no_of_brother", models.IntegerField()),
                ("brother_married", models.BooleanField()),
                ("no_of_sister", models.IntegerField()),
                ("sister_married", models.BooleanField()),
                ("educational_qualification", models.CharField(max_length=120)),
                ("job", models.CharField(max_length=120)),
                ("income_per_month", models.CharField(max_length=120)),
                ("Religious", models.CharField(max_length=120)),
                ("Gothram", models.CharField(max_length=120)),
                (
                    "Lagnam",
                    models.CharField(
                        choices=[
                            ("Mesam", "Mesam"),
                            ("Rishbam", "Rishbam"),
                            ("Mithunam", "Mithunam"),
                            ("Kadagam", "Kadagam"),
                            ("Simmam", "Simmam"),
                            ("Kanni", "Kanni"),
                            ("Thulam", "Thulam"),
                            ("Viruchagam", "Viruchagam"),
                            ("Dhanusu", "Dhanusu"),
                            ("Magaram", "Magaram"),
                            ("Kumbam", "Kumbam"),
                            ("Meenam", "Meenam"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "Raasi",
                    models.CharField(
                        choices=[
                            ("Mesam", "Mesam"),
                            ("Rishbam", "Rishbam"),
                            ("Mithunam", "Mithunam"),
                            ("Kadagam", "Kadagam"),
                            ("Simmam", "Simmam"),
                            ("Kanni", "Kanni"),
                            ("Thulam", "Thulam"),
                            ("Viruchagam", "Viruchagam"),
                            ("Dhanusu", "Dhanusu"),
                            ("Magaram", "Magaram"),
                            ("Kumbam", "Kumbam"),
                            ("Meenam", "Meenam"),
                        ],
                        max_length=120,
                    ),
                ),
                (
                    "Star",
                    models.CharField(
                        choices=[
                            ("Ashwini", "Ashwini"),
                            ("Bharani", "Bharani"),
                            ("Krittika", "Krittika"),
                            ("Rohini", "Rohini"),
                            ("Mrighasira", "Mrighasira"),
                            ("Thiruvadhirai", "Thiruvadhirai"),
                            ("Punarpoosam", "Punarpoosam"),
                            ("Poosam", "Poosam"),
                            ("Ayilyam", "Ayilyam"),
                            ("Magam", "Magam"),
                            ("Pooram", "Pooram"),
                            ("Uthiram", "Uthiram"),
                            ("Astham", "Astham"),
                            ("Chitrai", "Chitrai"),
                            ("Swathi", "Swathi"),
                            ("Visagam", "Visagam"),
                            ("Ausham", "Ausham"),
                            ("Kettai", "Kettai"),
                            ("Moolam", "Moolam"),
                            ("Pooradam", "Pooradam"),
                            ("Uthradam", "Uthradam"),
                            ("Thiruvonam", "Thiruvonam"),
                            ("Avittam", "Avittam"),
                            ("Sathayam", "Sathayam"),
                            ("Poorattathi", "Poorattathi"),
                            ("Utharattadhi", "Utharattadhi"),
                            ("Revathi", "Revathi"),
                        ],
                        max_length=120,
                    ),
                ),
                ("Dosa", models.CharField(max_length=120)),
                (
                    "Raasi_Image",
                    models.ImageField(upload_to=apps.informations.models.upload_to),
                ),
                (
                    "Navamsam_Image",
                    models.ImageField(upload_to=apps.informations.models.upload_to),
                ),
                ("contact_person", models.CharField(max_length=120)),
                ("contact_No", models.IntegerField()),
                ("whatsApp", models.IntegerField()),
                ("address", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("district", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                (
                    "Caste",
                    models.ForeignKey(
                        max_length=120,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="informations.caste",
                    ),
                ),
                (
                    "Sub_Caste",
                    models.ForeignKey(
                        max_length=120,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="informations.subcaste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basic Information",
                "verbose_name_plural": "Basic_Informations",
            },
        ),
    ]
