# Generated by Django 4.2 on 2023-05-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicinformation",
            name="brother_married",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="basicinformation",
            name="sister_married",
            field=models.CharField(max_length=120),
        ),
    ]
